### ISSUE TITLE
Version checking bug causing the mod to not load

### ISSUE THREAD

**Issue by randomultrakillplayer** [10-days-till-xmas/UltraStrafe#4]
![image](https://github.com/user-attachments/assets/575171f8-f0d3-4719-8986-6a84c2c11a95)

**Comment by 10-days-till-xmas** [comment]
are there any other UltraStrafe.dll files in the BepInEx/plugins folder? Including any folders within it?

**Comment by triggered0idiot** [comment]
It might be worth sending your bugged version of the plugin over if there isnt extra dlls

**Comment by randomultrakillplayer** [comment]
![image](https://github.com/user-attachments/assets/913df84a-a05b-4698-b358-11d413fbdeef)

**Comment by randomultrakillplayer** [comment]
oh and i have literally no idea how to upload files

**Comment by 10-days-till-xmas** [comment]
> oh and I have literally no idea how to upload files

You can drag files into the text box here
I think I may know what the reason behind it is? Though I'm doubtful. Some people when getting this bug have the mod unable to load, but I've encountered it too and had the mod work perfectly fine. I'll do some testing to see if its what I think it is (having 2 classes with the same BepInPlugin attributes)

**Comment by triggered0idiot** [comment]
dont have two bepinex plugins in one dll thats defo whats causing it

**Comment by triggered0idiot** [comment]
I dont know the exact reasoning but dont have two bepinex plugins in one dll that share a guid

**Comment by triggered0idiot** [comment]
Do not have two bepinex plugins with the same guid, they will override eachother and i think because you have two identical attributes they are "fighting" to be the first to load and when the one without plugin code "wins" it wint do anything

**Comment by 10-days-till-xmas** [comment]
> Do not have two bepinex plugins with the same guid, they will override eachother and i think because you have two identical attributes they are "fighting" to be the first to load and when the one without plugin code "wins" it wont do anything

Ah yea that makes sense, I'll restructure the ConfigManager class then

**Comment by 10-days-till-xmas** [comment]
142395e58964646916237625a5cdaf975444313a fixes this in v1.1.1
